import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/styles/style.scss'
import BottomSheetControler from '@/components/ui/BottomSheetControler'
import PopupControler from '@/components/ui/PopupControler'
import CommonHeader from '@/components/ui/CommonHeader'
import Footer from '@/components/ui/Footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="wrap">
          <CommonHeader />
          <div className="container">{children}</div>
          <Footer />
        </div>
        <BottomSheetControler />
        <PopupControler />
      </body>
    </html>
  )
}
