import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/style.scss";
import BottomSheetControler from "@/components/ui/BottomSheetControler";
import PopupControler from "@/components/ui/PopupControler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <BottomSheetControler />
        <PopupControler />
      </body>
    </html>
  );
}
